name: raven-nf

channels:
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - bcftools
  - bwa=0.7.17
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - curl=7.69.1
  - diamond
  - gettext=0.19.8.1
  - htslib=1.9
  - kraken2=2.0.9beta
  - krb5=1.17.1
  - krona=2.7.1
  - libcurl=7.69.1
  - libcxx=10.0.0
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - libidn2=2.3.0
  - libssh2=1.9.0
  - libunistring=0.9.10
  - ncurses=6.1
  - openssl=1.1.1g
  - perl=5.26.2
  - python=3.7.3
  - requests
  - samtools=1.10
  - seqtk=1.3
  - spades=3.14.0
  - sra-tools=2.10.1
  - tk=8.6.10
  - trim-galore
  - wget=1.20.1
  - xz=5.2.5
  - zlib=1.2.11
