name: raven-nf

channels:
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - bcftools
  - bwa
  - diamond
  - htslib
  - kraken2
  - krona
  - perl
  - python>=3.7
  - requests
  - samtools=1.10
  - seqtk
  - spades=3.14.0
  - sra-tools=2.10.1
  - trim-galore
  - wget
